### ISSUE TITLE
Continuous Delivery needed for all AIT components

### ISSUE THREAD

**Issue by jordanpadams** [NASA-AMMOS/AIT-Core#131] opened 2018-11-09 00:26 UTC
If folks need a version of AIT ASAP, they can't be reliant on a committer to build and push. snapshots/dev versions need to be available continuously so teams can access urgent bug fixes.

**Comment by MJJoyce** [comment] 2018-11-10 00:44
FYI, check out #109 for some related info here. Attempted this at one point with TravisCI and couldn't get it working. More an issue with me and less TravisCI I'm sure, but someone gives it a poke that might help

**Comment by MJJoyce** [comment] 2018-11-10 00:45
Actually I think I'm going to just call this a duplicate of #109. @jordanpadams, thoughts?

**Closed** 2018-11-12 20:07 UTC
Labels: duplicate
